### ISSUE TITLE
[Bug]: Nonspecified Rx/Tx Closed Message

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/ASM-data-server#19]
### Commit Hash

31466a6

### Steps to Reproduce?

1. Run Server
2. Run On-Box Node
3. Run Remote Node
4. Wait

### Observed Behavior

We observe occasional Rx closed and Tx closed messages

### Desired Behavior

We need more insight into which Rx and Tx are closed.

### Component

On Box Sensor Node

### Relevant Sensor Node log output

```shell
N/A
```

### Relevant Sensor Node configuration

```shell
N/A
```

### Relevant Server log output

```shell
2021-11-21 22:40:09,936 - root - ERROR - Failed to create server: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/home/ntlhui/anaconda3/bin/runServer.py", line 48, in main
    server = Server(site_config)
  File "/home/ntlhui/anaconda3/lib/python3.8/site-packages/DataServer/server.py", line 231, in __init__
    self._log.info(f"Starting ASM Data Server v{DataServer.__version__}, {self.__getRevision()}")
  File "/home/ntlhui/anaconda3/lib/python3.8/site-packages/DataServer/server.py", line 223, in __getRevision
    git_rev_parse = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD']).decode('ascii').strip()
  File "/home/ntlhui/anaconda3/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/ntlhui/anaconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.
2021-11-21 23:02:16,609 - Server - INFO - Starting ASM Data Server v0.0.0.1,  dirty
2021-11-21 23:02:16,611 - root - INFO - Discovered data_dir: /ayeayedata
2021-11-21 23:02:16,611 - root - INFO - Discovered port: 9000
2021-11-21 23:02:16,611 - root - INFO - Discovered server_uuid: 33cc5438-3d39-11ec-8957-378c22225c74
2021-11-21 23:02:16,611 - root - INFO - Discovered video_increment: 300
2021-11-21 23:02:16,611 - root - INFO - Discovered rtsp_port_block: [10000, 10100]
2021-11-21 23:02:16,611 - root - INFO - Data Directory: /ayeayedata
2021-11-21 23:02:16,614 - asyncio - DEBUG - Using selector: EpollSelector
2021-11-21 23:02:16,614 - Server - INFO - Connecting to :9000
2021-11-21 23:02:19,986 - Server - INFO - Starting ASM Data Server v0.0.0.1,  dirty
2021-11-21 23:02:19,987 - root - INFO - Discovered data_dir: /ayeayedata
2021-11-21 23:02:19,988 - root - INFO - Discovered port: 9000
2021-11-21 23:02:19,988 - root - INFO - Discovered server_uuid: 33cc5438-3d39-11ec-8957-378c22225c74
2021-11-21 23:02:19,988 - root - INFO - Discovered video_increment: 300
2021-11-21 23:02:19,988 - root - INFO - Discovered rtsp_port_block: [10000, 10100]
2021-11-21 23:02:19,988 - root - INFO - Data Directory: /ayeayedata
2021-11-21 23:02:19,990 - asyncio - DEBUG - Using selector: EpollSelector
2021-11-21 23:02:19,990 - Server - INFO - Connecting to :9000
2021-11-22 00:23:40,715 - ClientHandler - INFO - Getting client for uuid 8124cb7c-41ec-11ec-aaad-e45f015ed519
2021-11-22 00:23:40,716 - ClientHandler - INFO - Got heartbeat from 8124cb7c-41ec-11ec-aaad-e45f015ed519 (Auto-registered device) at 2021-11-22 00:23:40.712000
2021-11-22 00:24:07,578 - ClientHandler - INFO - Rx closed
2021-11-22 00:24:07,578 - ClientHandler - INFO - Tx closed
2021-11-22 00:35:14,329 - ClientHandler - INFO - Rx closed
2021-11-22 00:35:14,335 - ClientHandler - INFO - Tx closed
2021-11-22 00:35:34,502 - ClientHandler - INFO - Rx closed
2021-11-22 00:35:34,503 - ClientHandler - INFO - Tx closed
2021-11-22 00:36:03,380 - ClientHandler - INFO - Rx closed
2021-11-22 00:36:03,380 - ClientHandler - INFO - Tx closed
2021-11-22 00:36:23,549 - ClientHandler - INFO - Rx closed
2021-11-22 00:36:23,549 - ClientHandler - INFO - Tx closed
2021-11-22 00:36:43,720 - ClientHandler - INFO - Rx closed
2021-11-22 00:36:43,721 - ClientHandler - INFO - Tx closed
2021-11-22 00:37:03,890 - ClientHandler - INFO - Rx closed
2021-11-22 00:37:03,891 - ClientHandler - INFO - Tx closed
2021-11-22 00:37:24,080 - ClientHandler - INFO - Rx closed
2021-11-22 00:37:24,081 - ClientHandler - INFO - Tx closed
2021-11-22 04:46:42,234 - ClientHandler - INFO - Rx closed
2021-11-22 04:46:42,235 - ClientHandler - INFO - Tx closed
2021-11-22 07:47:25,603 - ClientHandler - INFO - Rx closed
2021-11-22 07:47:25,604 - ClientHandler - INFO - Tx closed
2021-11-22 08:06:47,558 - ClientHandler - INFO - Getting client for uuid a4a5090c-fc41-47d4-a180-e82cf8bfc899
2021-11-22 08:06:47,558 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:06:47.551000
2021-11-22 08:06:47,558 - ClientHandler - INFO - Got RTP Start Command
2021-11-22 08:06:47,558 - ClientHandler - INFO - Got port 10001
2021-11-22 08:06:47,559 - ClientHandler - INFO - Started ffmpeg with command: ffmpeg -i tcp://@:10001?listen -c copy -flags +global_header -f segment -segment_time 300 -strftime 1 -reset_timestamps 1 /ayeayedata/a4a5090c-fc41-47d4-a180-e82cf8bfc899/%Y.%m.%d.%H.%M.%S.mp4
2021-11-22 08:06:47,565 - ClientHandler - INFO - RTP Server on port 10001 started outputting to /ayeayedata/a4a5090c-fc41-47d4-a180-e82cf8bfc899
2021-11-22 08:07:47,549 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:07:47.551000
2021-11-22 08:08:47,548 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:08:47.552000
2021-11-22 08:09:47,550 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:09:47.553000
2021-11-22 08:10:23,540 - ClientHandler - INFO - Getting client for uuid a105a7ea-3eae-11ec-8446-a0afbd87594c
2021-11-22 08:10:23,540 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:10:23.533000
2021-11-22 08:10:23,541 - ClientHandler - INFO - Got RTP Start Command
2021-11-22 08:10:23,541 - ClientHandler - INFO - Got port 10002
2021-11-22 08:10:23,542 - ClientHandler - INFO - Started ffmpeg with command: ffmpeg -i tcp://@:10002?listen -c copy -flags +global_header -f segment -segment_time 300 -strftime 1 -reset_timestamps 1 /ayeayedata/a105a7ea-3eae-11ec-8446-a0afbd87594c/%Y.%m.%d.%H.%M.%S.mp4
2021-11-22 08:10:23,545 - ClientHandler - INFO - RTP Server on port 10002 started outputting to /ayeayedata/a105a7ea-3eae-11ec-8446-a0afbd87594c
2021-11-22 08:10:47,550 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:10:47.554000
2021-11-22 08:11:23,541 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:11:23.533000
2021-11-22 08:11:47,550 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:11:47.554000
2021-11-22 08:12:23,542 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:12:23.534000
2021-11-22 08:12:47,551 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:12:47.555000
2021-11-22 08:13:23,542 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:13:23.535000
2021-11-22 08:13:47,551 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:13:47.555000
2021-11-22 08:14:23,567 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:14:23.535000
2021-11-22 08:14:47,556 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:14:47.556000
2021-11-22 08:15:23,543 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:15:23.536000
2021-11-22 08:15:47,552 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:15:47.556000
2021-11-22 08:16:23,545 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:16:23.537000
2021-11-22 08:16:47,553 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:16:47.557000
2021-11-22 08:17:23,551 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:17:23.537000
2021-11-22 08:17:47,553 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:17:47.558000
2021-11-22 08:18:23,548 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:18:23.538000
2021-11-22 08:18:47,554 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:18:47.558000
2021-11-22 08:19:23,582 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:19:23.539000
2021-11-22 08:19:47,554 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:19:47.559000
2021-11-22 08:20:23,550 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:20:23.539000
2021-11-22 08:20:47,555 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:20:47.559000
2021-11-22 08:21:23,549 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:21:23.540000
2021-11-22 08:21:47,557 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:21:47.560000
2021-11-22 08:22:23,551 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:22:23.540000
2021-11-22 08:22:47,560 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:22:47.560000
2021-11-22 08:23:23,551 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:23:23.541000
2021-11-22 08:23:47,564 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:23:47.561000
2021-11-22 08:24:23,554 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:24:23.542000
2021-11-22 08:24:47,568 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:24:47.562000
2021-11-22 08:25:23,554 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:25:23.542000
2021-11-22 08:25:47,567 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:25:47.562000
2021-11-22 08:26:23,560 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:26:23.543000
2021-11-22 08:26:47,569 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:26:47.563000
2021-11-22 08:27:23,561 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:27:23.543000
2021-11-22 08:27:47,565 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:27:47.563000
2021-11-22 08:28:23,561 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:28:23.544000
2021-11-22 08:28:47,571 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:28:47.564000
2021-11-22 08:29:23,559 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:29:23.545000
2021-11-22 08:29:47,567 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:29:47.564000
2021-11-22 08:30:23,558 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:30:23.545000
2021-11-22 08:30:47,569 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:30:47.565000
2021-11-22 08:31:23,564 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:31:23.546000
2021-11-22 08:31:47,574 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:31:47.565000
2021-11-22 08:32:23,564 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:32:23.546000
2021-11-22 08:32:47,575 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:32:47.566000
2021-11-22 08:33:23,561 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:33:23.547000
2021-11-22 08:33:47,575 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:33:47.567000
2021-11-22 08:34:23,566 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:34:23.547000
2021-11-22 08:34:47,577 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:34:47.567000
2021-11-22 08:35:23,567 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:35:23.548000
2021-11-22 08:35:47,577 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:35:47.568000
2021-11-22 08:36:23,568 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:36:23.549000
2021-11-22 08:36:47,575 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:36:47.568000
2021-11-22 08:37:23,569 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:37:23.549000
2021-11-22 08:37:47,575 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:37:47.569000
2021-11-22 08:38:23,566 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:38:23.550000
2021-11-22 08:38:47,579 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:38:47.569000
2021-11-22 08:39:23,570 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:39:23.550000
2021-11-22 08:39:47,580 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:39:47.570000
2021-11-22 08:40:23,571 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:40:23.551000
2021-11-22 08:40:47,583 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:40:47.570000
2021-11-22 08:41:23,572 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:41:23.551000
2021-11-22 08:41:47,582 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:41:47.571000
2021-11-22 08:42:23,573 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:42:23.552000
2021-11-22 08:42:47,583 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:42:47.572000
2021-11-22 08:43:23,574 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:43:23.553000
2021-11-22 08:43:47,584 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:43:47.572000
2021-11-22 08:44:23,574 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:44:23.553000
2021-11-22 08:44:47,584 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:44:47.573000
2021-11-22 08:45:23,576 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:45:23.554000
2021-11-22 08:45:47,585 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:45:47.573000
2021-11-22 08:46:23,584 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:46:23.554000
2021-11-22 08:46:47,588 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:46:47.574000
2021-11-22 08:47:23,583 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:47:23.555000
2021-11-22 08:47:47,586 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:47:47.574000
2021-11-22 08:48:23,578 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:48:23.555000
2021-11-22 08:48:47,587 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:48:47.575000
2021-11-22 08:49:23,573 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:49:23.556000
2021-11-22 08:49:47,588 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:49:47.575000
2021-11-22 08:50:23,574 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:50:23.557000
2021-11-22 08:50:47,584 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:50:47.576000
2021-11-22 08:51:23,579 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:51:23.557000
2021-11-22 08:51:47,589 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:51:47.577000
2021-11-22 08:52:23,580 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:52:23.558000
2021-11-22 08:52:47,585 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:52:47.577000
2021-11-22 08:53:23,580 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:53:23.558000
2021-11-22 08:53:47,592 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:53:47.578000
2021-11-22 08:54:23,580 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:54:23.559000
2021-11-22 08:54:47,588 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:54:47.578000
2021-11-22 08:55:23,575 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:55:23.560000
2021-11-22 08:55:47,590 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:55:47.579000
2021-11-22 08:56:23,593 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:56:23.560000
2021-11-22 08:56:47,593 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:56:47.579000
2021-11-22 08:56:50,500 - ClientHandler - INFO - Rx closed
2021-11-22 08:56:50,501 - ClientHandler - INFO - Tx closed
2021-11-22 08:57:23,586 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:57:23.561000
2021-11-22 08:57:47,591 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:57:47.580000
2021-11-22 08:57:50,666 - ClientHandler - INFO - Rx closed
2021-11-22 08:57:50,667 - ClientHandler - INFO - Tx closed
2021-11-22 08:58:23,580 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:58:23.561000
2021-11-22 08:58:47,588 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:58:47.580000
2021-11-22 08:58:50,838 - ClientHandler - INFO - Rx closed
2021-11-22 08:58:50,838 - ClientHandler - INFO - Tx closed
2021-11-22 08:59:23,576 - ClientHandler - INFO - Got heartbeat from a105a7ea-3eae-11ec-8446-a0afbd87594c (Auto-registered device) at 2021-11-22 08:59:23.562000
2021-11-22 08:59:47,591 - ClientHandler - INFO - Got heartbeat from a4a5090c-fc41-47d4-a180-e82cf8bfc899 (Auto-registered device) at 2021-11-22 08:59:47.581000
```

### Relevant Server configuration

```shell
# This is a sample configuration for the Aye-Aye Sleep Monitoring Data Server.
# Use this as a basis for configuring the data server for the specific server.

# Local path in which to store the data hierarchy
data_dir: /ayeayedata

# This is the primary port for the data server.
port: 9000

# Data Server UID
# 
# This is the UUID that uniquely identifies this device.
server_uuid: '33cc5438-3d39-11ec-8957-378c22225c74'

# This is the maximum length of video data
video_increment: 300

# RTSP Server Port Block
#
# This is the block of ports that RTSP servers should use.
rtsp_port_block: [10000, 10100]
```

**Comment by ntlhui** [comment]
Relevant code is `DataServer.server.ClientHandler.command_handler` and `DataServer.server.ClientHandler.response_sender` in [DataServer/server.py:118](https://github.com/UCSD-E4E/ASM-data-server/blob/2b343ed36ae280a23b83c0aabecb6f97cf509cfb/DataServer/server.py#L118), [DataServer/server.py:131](https://github.com/UCSD-E4E/ASM-data-server/blob/2b343ed36ae280a23b83c0aabecb6f97cf509cfb/DataServer/server.py#L131)

**Comment by ntlhui** [comment]
Fixing in #34
